### ISSUE TITLE
Error in send_object function with BinaryBob/BinaryBlobArray

### ISSUE THREAD

**Issue by harlem88** [astarte-platform/astarte-device-sdk-rust#111]
The send_object function returns the error: `send error (You are sending the wrong type for this object mapping: got IntegerArray([104, 101, 108, 108, 111]), expected BinaryBlob)`.
This is related to the BSON parsing. It can be patched (not graciously) using the package: [serde_bytes](https://crates.io/crates/serde_bytes).
Regarding this see this issue  https://github.com/mongodb/bson-rust/issues/400.

Also for BinaryBlobArray type.

**Comment by sorru94** [comment]
This issue is related to the [to_document()](https://docs.rs/bson/latest/bson/fn.to_document.html) function in the `bson` library. Used here:
https://github.com/astarte-platform/astarte-device-sdk-rust/blob/8286c58a325ae0b4eddedb69c756e7a243ad7a77/src/lib.rs#L821-L831

When `data` is a struct containing a field as such:
```
AggregateStruct {
    binaryblob_element: [104,101,108,108,111,]
}
```
The resulting `doc` variable will be a `bson::Document` as such:
```
Document({
    "binaryblob_element": Array([
        Int32(104,),
        Int32(101,),
        Int32(108,),
        Int32(108,),
        Int32(111,),
    ]),
})
```
